export const ActivityAction = {
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  ESTIMATE_GENERATED: 'ESTIMATE_GENERATED',
  ESTIMATE_UPDATED: 'ESTIMATE_UPDATED',
  ESTIMATE_EXPORTED: 'ESTIMATE_EXPORTED',
} as const;

export type ActivityAction = (typeof ActivityAction)[keyof typeof ActivityAction];
